# Generated by Django 5.0.2 on 2024-04-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cine",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("razon_social", models.CharField(max_length=30)),
                ("salas", models.IntegerField()),
                ("id_distrito", models.IntegerField()),
                ("direccion", models.CharField(max_length=100)),
                ("telefonos", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=80)),
                ("fecha_estreno", models.DateField()),
                ("director", models.CharField(max_length=50)),
                ("generos", models.CharField(max_length=100)),
                ("id_clasificacion", models.IntegerField()),
                ("id_estado", models.IntegerField()),
                ("duracion", models.CharField(max_length=10)),
                ("link", models.CharField(max_length=200)),
                ("reparto", models.TextField()),
                ("sinopsis", models.TextField()),
            ],
        ),
    ]
